version: '3'
services:
  db:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=media
    ports:
      - '5432:5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
  browser:
    image: 'browserless/chrome:latest'
    ports:
      - "3000:3000"
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_HOST=db
      - PG_PORT=5432
      - PG_PASSWORD=postgres
      - PG_DATABASE=media
      - PG_USER=postgres
    depends_on:
      - redis
      - db
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - ./client:/app
  scraper:
    build:
      dockerfile: Dockerfile
      context: ./scraper
    restart: unless-stopped
    volumes:
      - ./scraper:/app
    depends_on:
      - redis
      - db
      - browser
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_HOST=db
      - PG_PORT=5432
      - PG_PASSWORD=postgres
      - PG_DATABASE=media
      - PG_USER=postgres
      - REDIS_CONSUMER_GROUP_NAME=scraper
      - REDIS_STREAM_NAME =url_stream
      - REDIS_ERROR_STREAM =backend.error
      - BROWSER_HOST=browser
      - BROWSER_PORT=3000
    #deploy:
    #  mode: replicated
    #  replicas: 5
